name: Build & Test

on:
  workflow_call:
    inputs:
      upload-artifact:
        required: false
        type: boolean
        default: false

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18 ]

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Lint
      run: pnpm lint

    - name: Build
      run: pnpm build

    - name: Test
      run: pnpm test

    - name: Upload build artifact
      if: ${{ inputs.upload-artifact == true }}
      uses: actions/upload-artifact@master
      with:
        name: gizmo-api
        path: |
          .
          !node_modules/
        if-no-files-found: error
