name: Publish

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  cd:

    runs-on: ubuntu-latest
    uses: GizmoDevelopment/gizmo-api/.github/workflows/build.yml@master

    steps:

      - name: Build Node module
        run: |
          pnpm build:cleanup
          pnpm build:node

      - name: Remove useless files and directories
        run: rm -rf ./build ./dist ./src ./dev

      # - name: Deploy
      #   uses: JS-DevTools/npm-publish@v1
      #   with:
      #     token: ${{ secrets.NPM_TOKEN }}
      #     check-version: true
