name: Publish

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:

  build:
    uses: GizmoDevelopment/gizmo-api/.github/workflows/build.yml@master

  cd:

    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: Remove useless files and directories
        run: rm -rf ./build ./dist ./src ./dev

      - name: Test
        run: ls

