name: Publish

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:

  build:
    uses: GizmoDevelopment/gizmo-api/.github/workflows/build.yml@master
    with:
      upload-artifact: true

  cd:

    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: Download build artifact
        uses: actions/download-artifact@master
        with:
          name: gizmo-api
          path: .
          if-no-files-found: error

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          check-version: true
